<script setup>
import { router,useForm } from '@inertiajs/vue3';
defineProps({ references:Object });
const labels={locations:'Lieux',disciplines:'Disciplines',levels:'Niveaux',categories:'Catégories tarifaires'};
const forms={locations:useForm({name:'',discount_percentage:0}),disciplines:useForm({name:'',discount_percentage:0}),levels:useForm({name:'',discount_percentage:0}),categories:useForm({name:'',discount_percentage:0})};
const submit=type=>forms[type].post(`/admin/referentiels/${type}`,{preserveScroll:true,onSuccess:()=>forms[type].reset()});
const remove=(type,item)=>confirm(`Supprimer « ${item.name} » ?`)&&router.delete(`/admin/referentiels/${type}/${item.id}`,{preserveScroll:true});
</script>
<template><section class="grid gap-6 xl:grid-cols-2"><div v-for="(label,type) in labels" :key="type" class="overflow-hidden rounded-3xl bg-white"><div class="border-b border-black/5 px-6 py-5"><h2 class="font-serif text-2xl">{{ label }}</h2></div><form @submit.prevent="submit(type)" class="flex gap-2 p-4"><input v-model="forms[type].name" class="min-w-0 flex-1 rounded-xl border border-black/10 px-3 py-2.5 text-sm" placeholder="Nouvel élément" /><input v-if="type==='categories'" v-model="forms[type].discount_percentage" type="number" class="w-24 rounded-xl border border-black/10 px-3" placeholder="%" /><button class="grid h-11 w-11 place-items-center rounded-full bg-ink text-white">＋</button></form><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-[#f7f5f0] text-[11px] font-bold uppercase tracking-wider text-black/45"><tr><th class="px-5 py-3">Nom</th><th v-if="type==='categories'" class="px-4 py-3">Rabais</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-black/5"><tr v-for="item in references[type]" :key="item.id"><td class="px-5 py-4 font-semibold">{{ item.name }}</td><td v-if="type==='categories'" class="px-4 py-4 text-green-700">−{{ Number(item.discount_percentage) }} %</td><td class="px-5 py-4 text-right"><button @click="remove(type,item)" class="text-red-500">×</button></td></tr></tbody></table><p v-if="!references[type].length" class="p-8 text-center text-sm text-black/35">Aucun élément</p></div></div></section></template>
