<script setup>
import { computed, ref } from 'vue';
import { router } from '@inertiajs/vue3';
const props = defineProps({ students: Array });
const search = ref('');
const filtered = computed(() => { const q=search.value.trim().toLowerCase(); return q ? props.students.filter(s => `${s.name} ${s.email} ${s.phone||''} ${s.courses.join(' ')}`.toLowerCase().includes(q)) : props.students; });
const money = value => Number(value || 0).toLocaleString('fr-CH', { minimumFractionDigits: 2 });
</script>
<template><section class="overflow-hidden rounded-3xl bg-white"><div class="flex flex-col gap-4 border-b border-black/5 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-serif text-2xl">Élèves</h2><p class="mt-1 text-xs text-black/45">{{ students.length }} fiches élèves</p></div><input v-model="search" type="search" placeholder="Rechercher un nom, e-mail ou cours…" class="rounded-full border border-black/10 bg-[#faf9f6] px-4 py-2.5 text-sm sm:w-80" /></div><div v-if="filtered.length" class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead class="bg-[#f7f5f0] text-[11px] font-bold uppercase tracking-wider text-black/45"><tr><th class="px-6 py-4">Élève</th><th class="px-5 py-4">Coordonnées</th><th class="px-5 py-4">Cours suivis</th><th class="px-5 py-4">Inscriptions</th><th class="px-6 py-4 text-right">Total facturable</th></tr></thead><tbody class="divide-y divide-black/5"><tr v-for="student in filtered" :key="student.id" class="hover:bg-[#faf9f6]" :class="student.has_account && 'cursor-pointer'" @click="student.has_account && router.visit(`/admin/eleves/${student.id}`)"><td class="px-6 py-5"><div class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-full bg-[#f1dfdc] font-serif font-bold text-coral">{{ student.name.split(' ').map(p=>p[0]).slice(0,2).join('').toUpperCase() }}</span><div><strong>{{ student.name }}</strong><p class="mt-1 text-[10px] font-bold uppercase" :class="student.has_account ? 'text-green-700' : 'text-black/35'">{{ student.has_account ? 'Compte actif' : 'Sans compte' }}</p></div></div></td><td class="px-5 py-5"><a @click.stop :href="`mailto:${student.email}`" class="block text-sm">{{ student.email }}</a><a v-if="student.phone" @click.stop :href="`tel:${student.phone}`" class="mt-1 block text-xs text-black/40">{{ student.phone }}</a></td><td class="px-5 py-5"><div class="flex flex-wrap gap-1"><span v-for="course in student.courses" :key="course" class="rounded-full bg-black/5 px-2 py-1 text-[11px] font-semibold">{{ course }}</span></div></td><td class="px-5 py-5"><strong>{{ student.accepted_count }} acceptée{{ student.accepted_count>1?'s':'' }}</strong><p class="text-xs text-black/40">{{ student.waitlist_count }} en attente</p></td><td class="px-6 py-5 text-right font-bold">{{ money(student.total_amount) }} CHF</td></tr></tbody></table></div><div v-else class="px-6 py-16 text-center text-black/40">Aucun élève trouvé.</div></section></template>
