<script setup>
import { Head, router, usePage } from '@inertiajs/vue3';

defineProps({ student: Object, enrollments: Array, trialRequests: Array });
const page = usePage();
const money = value => Number(value || 0).toLocaleString('fr-CH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const date = value => value ? new Date(`${String(value).slice(0, 10)}T12:00:00`).toLocaleDateString('fr-CH') : '—';
const statusLabel = status => status === 'waitlist' ? 'Liste d’attente' : status === 'invited' ? 'Invitation envoyée' : status === 'expired' ? 'Invitation expirée' : status === 'accepted' ? 'Inscrit' : 'En traitement';
const logout = () => router.post('/admin/deconnexion');
</script>

<template>
    <Head :title="student.name" />
    <div class="min-h-screen bg-[#f5f3ee]">
        <header class="border-b border-black/5 bg-white"><div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="/admin?section=students" class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-full bg-ink text-white">♪</span><span class="font-serif text-2xl font-semibold">Corus</span><span class="rounded-full bg-[#f2eee8] px-3 py-1 text-[10px] font-bold uppercase text-black/45">Admin</span></a><button @click="logout" class="rounded-full border border-black/10 px-4 py-2 text-sm font-semibold">Déconnexion</button></div></header>
        <main class="mx-auto max-w-7xl px-5 py-10 lg:px-8">
            <a href="/admin?section=students" class="text-sm font-bold text-black/45 hover:text-coral">← Retour aux élèves</a>
            <div class="mt-7 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div class="flex items-center gap-5"><span class="grid h-20 w-20 place-items-center rounded-full bg-[#f1dfdc] font-serif text-3xl font-bold text-coral">{{ student.name.split(' ').map(p => p[0]).slice(0, 2).join('').toUpperCase() }}</span><div><p class="text-xs font-bold uppercase tracking-[.2em] text-coral">Fiche élève</p><h1 class="mt-1 font-serif text-4xl sm:text-5xl">{{ student.name }}</h1><p class="mt-2 text-sm text-black/45">Compte créé le {{ date(student.created_at) }}</p></div></div><div class="flex gap-2"><a :href="`mailto:${student.email}`" class="rounded-full bg-ink px-5 py-3 text-sm font-bold text-white">Envoyer un e-mail</a><a v-if="student.phone" :href="`tel:${student.phone}`" class="rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-bold">Appeler</a></div></div>

            <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-3xl bg-white p-6"><p class="text-sm text-black/45">Inscriptions</p><strong class="mt-3 block font-serif text-4xl">{{ student.enrollments_count }}</strong></div><div class="rounded-3xl bg-white p-6"><p class="text-sm text-black/45">Cours acceptés</p><strong class="mt-3 block font-serif text-4xl">{{ student.accepted_count }}</strong></div><div class="rounded-3xl bg-[#eed5d5] p-6"><p class="text-sm text-black/45">Liste d’attente</p><strong class="mt-3 block font-serif text-4xl">{{ student.waitlist_count }}</strong></div><div class="rounded-3xl bg-ink p-6 text-white"><p class="text-sm text-white/50">Total facturable</p><strong class="mt-3 block font-serif text-3xl">{{ money(student.total_amount) }} CHF</strong></div></div>

            <div class="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><aside class="space-y-6"><section class="rounded-3xl bg-white p-6"><h2 class="font-serif text-2xl">Coordonnées</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-black/40">E-mail</dt><dd class="mt-1 font-semibold"><a :href="`mailto:${student.email}`" class="hover:text-coral">{{ student.email }}</a></dd></div><div><dt class="text-black/40">Téléphone</dt><dd class="mt-1 font-semibold">{{ student.phone || 'Non renseigné' }}</dd></div><div><dt class="text-black/40">Compte utilisateur</dt><dd class="mt-1"><span class="rounded-full bg-green-50 px-2.5 py-1 text-xs font-bold text-green-700">Actif</span></dd></div></dl></section><section v-if="student.is_minor" class="rounded-3xl bg-[#eee9f5] p-6"><div class="flex items-center justify-between gap-3"><h2 class="font-serif text-2xl">Représentant légal</h2><span class="rounded-full bg-purple-100 px-3 py-1 text-[10px] font-bold uppercase text-purple-700">Élève mineur</span></div><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-black/40">Prénom</dt><dd class="mt-1 font-semibold">{{ student.legal_guardian_first_name }}</dd></div><div><dt class="text-black/40">Nom</dt><dd class="mt-1 font-semibold">{{ student.legal_guardian_last_name }}</dd></div></dl></section><section v-if="trialRequests.length" class="overflow-hidden rounded-3xl bg-white"><div class="border-b border-black/5 p-6"><h2 class="font-serif text-2xl">Cours d’essai</h2></div><div class="divide-y divide-black/5"><div v-for="trial in trialRequests" :key="trial.id" class="p-5"><strong>{{ trial.course?.title }}</strong><p class="mt-1 text-xs text-black/45">{{ date(trial.preferred_date) }} · {{ trial.course?.time }}</p><p v-if="trial.message" class="mt-2 text-sm italic text-black/55">« {{ trial.message }} »</p></div></div></section></aside>

                <section class="overflow-hidden rounded-3xl bg-white"><div class="border-b border-black/5 px-6 py-5"><h2 class="font-serif text-2xl">Historique des inscriptions</h2><p class="mt-1 text-xs text-black/45">Cours, tarifs, rabais, plans de paiement et factures.</p></div><div v-if="enrollments.length" class="divide-y divide-black/5"><article v-for="item in enrollments" :key="item.id" class="p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><div class="flex flex-wrap items-center gap-2"><h3 class="font-serif text-xl">{{ item.course?.title || 'Cours supprimé' }}</h3><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase" :class="item.status === 'waitlist' ? 'bg-purple-50 text-purple-700' : 'bg-amber-50 text-amber-700'">{{ statusLabel(item.status) }}</span><span v-if="item.dance_role" class="rounded-full bg-black/5 px-2 py-1 text-[10px] font-bold uppercase">{{ item.dance_role }}</span></div><p class="mt-2 text-sm text-black/45">{{ item.course?.style }} · {{ item.course?.level }} · {{ item.course?.day }} {{ item.course?.time }}</p><p class="mt-1 text-xs text-black/40">Début choisi : {{ date(item.start_date) }} · {{ item.lessons_count }} leçons</p></div><div class="sm:text-right"><strong class="font-serif text-2xl">{{ money(item.amount) }} CHF</strong><p class="text-xs text-black/35">Inscrit le {{ date(item.created_at) }}</p></div></div><div class="mt-4 grid gap-2 rounded-2xl bg-[#f7f5f0] p-4 text-xs sm:grid-cols-2"><p>Tarif avant rabais : <strong>{{ money(item.base_amount) }} CHF</strong></p><p v-if="item.pricing_category_name">Catégorie : <strong>{{ item.pricing_category_name }}</strong></p><p v-if="Number(item.discount_amount)">Rabais multi-cours : <strong>−{{ money(item.discount_amount) }} CHF<span v-if="Number(item.discount_percentage)"> ({{ Number(item.discount_percentage) }} %)</span></strong></p><p v-if="item.payment_plan_name">Plan : <strong>{{ item.payment_plan_name }} · {{ item.installment_count }} × {{ money(item.installment_amount) }} CHF</strong></p></div><div v-if="item.invoice" class="mt-4 flex items-center justify-between rounded-2xl border border-black/5 p-4"><div><strong>{{ item.invoice.number }}</strong><p class="text-xs text-black/40">Échéance {{ date(item.invoice.due_at) }} · {{ item.invoice.status === 'paid' ? 'Payée' : 'Ouverte' }}</p></div><a :href="`/admin/factures/${item.invoice.id}`" target="_blank" class="rounded-full bg-ink px-4 py-2 text-xs font-bold text-white">Voir la facture</a></div></article></div><div v-else class="p-16 text-center text-black/40">Aucune inscription.</div></section>
            </div>
        </main>
    </div>
</template>
