<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $invoice->number }}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eee;color:#171717;font:14px Arial,sans-serif}.sheet{width:210mm;min-height:297mm;margin:20px auto;background:#fff;padding:18mm 15mm 0}.top{display:flex;justify-content:space-between;gap:30px}.brand{font-size:27px;font-weight:700}.muted{color:#666}.meta{border-collapse:collapse}.meta td{padding:3px 0 3px 20px}.meta td:first-child{padding-left:0;color:#666}.title{margin:20mm 0 8mm;font-size:30px}.recipient{line-height:1.6}.lines{width:100%;margin-top:10mm;border-collapse:collapse}.lines th{text-align:left;border-bottom:2px solid #222;padding:10px 5px}.lines td{padding:10px 5px;border-bottom:1px solid #ddd}.right{text-align:right!important}.total{font-size:18px;font-weight:bold}.paid{color:#247044}.balance{background:#f5f3ee;font-size:20px}.history{margin-top:6mm;font-size:11px}.history h3{margin-bottom:3mm}.history span{display:inline-block;margin:0 4mm 2mm 0}.notice{margin-top:10mm;padding:12px;background:#fff4d7}.payment{margin:10mm -15mm 0;page-break-inside:avoid}.actions{position:fixed;right:20px;top:20px;display:flex;gap:8px}.actions button,.actions a{border:0;border-radius:99px;background:#171717;color:white;padding:11px 16px;text-decoration:none;font-weight:bold;cursor:pointer}@media print{body{background:#fff}.sheet{margin:0}.actions{display:none}}
</style></head><body>
<div class="actions">@auth<a href="{{ route('admin.invoices.show', $invoice) }}">← Gestion de la facture</a>@endauth<button onclick="window.print()">Imprimer / PDF</button></div>
<main class="sheet"><div class="top"><div><div class="brand">{{ $invoice->school->name }}</div><p class="muted">{{ $invoice->school->billing_street }} {{ $invoice->school->billing_house_number }}<br>{{ $invoice->school->billing_postal_code }} {{ $invoice->school->billing_city }}</p></div><table class="meta"><tr><td>Facture</td><td><strong>{{ $invoice->number }}</strong></td></tr>@if($invoice->installment_count > 1)<tr><td>Échéance</td><td><strong>{{ $invoice->installment_number }} / {{ $invoice->installment_count }}</strong></td></tr>@endif<tr><td>Date</td><td>{{ $invoice->issued_at->format('d.m.Y') }}</td></tr><tr><td>À payer le</td><td>{{ $invoice->due_at->format('d.m.Y') }}</td></tr><tr><td>Statut</td><td>{{ $invoice->payment_status === 'paid' ? 'Payée' : ($invoice->payment_status === 'partial' ? 'Partiellement payée' : 'Ouverte') }}</td></tr></table></div>
<h1 class="title">Facture d’inscription</h1><div class="recipient"><strong>{{ $invoice->enrollment->first_name }} {{ $invoice->enrollment->last_name }}</strong><br>{{ $invoice->enrollment->email }}<br>{{ $invoice->enrollment->phone }}</div>
<table class="lines"><thead><tr><th>Prestation</th><th>Début</th><th>Leçons</th><th class="right">Montant</th></tr></thead><tbody><tr><td>Inscription — {{ $invoice->enrollment->course?->title }}</td><td>{{ $invoice->enrollment->start_date->format('d.m.Y') }}</td><td>{{ $invoice->enrollment->lessons_count }}</td><td class="right">{{ number_format((float)$invoice->amount,2,',',' ') }} CHF</td></tr><tr><td colspan="3" class="right">Total facture</td><td class="right">{{ number_format((float)$invoice->amount,2,',',' ') }} CHF</td></tr>@if($invoice->paid_amount > 0)<tr class="paid"><td colspan="3" class="right">Paiements reçus</td><td class="right">−{{ number_format($invoice->paid_amount,2,',',' ') }} CHF</td></tr>@endif<tr class="balance"><td colspan="3" class="right total">Solde à payer</td><td class="right total">{{ number_format($invoice->balance,2,',',' ') }} CHF</td></tr></tbody></table>
@if($invoice->payments->isNotEmpty())<div class="history"><h3>Paiements enregistrés</h3>@foreach($invoice->payments as $payment)<span>{{ $payment->paid_on->format('d.m.Y') }} · {{ number_format((float)$payment->amount,2,',',' ') }} CHF · {{ ucfirst(str_replace('_',' ',$payment->method)) }}</span>@endforeach</div>@endif
@if($invoice->installment_count > 1)<div class="history"><h3>Calendrier du plan de paiement</h3>@foreach($invoice->enrollment->invoices as $scheduled)<span>{{ $scheduled->installment_number }}/{{ $scheduled->installment_count }} · {{ $scheduled->due_at->format('d.m.Y') }} · {{ number_format((float)$scheduled->amount,2,',',' ') }} CHF{{ $scheduled->payment_status === 'paid' ? ' · payée' : '' }}</span>@endforeach</div>@endif
@if($qrError)<div class="notice"><strong>QR-facture pas encore disponible.</strong><br>{{ $qrError }} Configurez les coordonnées bancaires dans l’administration.</div>@endif
@if($paymentPart)<div class="payment">{!! $paymentPart !!}</div>@endif
</main></body></html>
